name: Private Fast action
on:
  push:
    branches: ['master']
    paths: ['output/**', 'py/**']

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Giving test class names
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: RUN FAST
        run: python py/prioritize.py
      - name: Commit files
        run: |
          cd ../
          git config --local user.name  ${{ github.actor }}
          git add ./output
          git commit -m "persisting tests results"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true