name: Private Fast action
on:
  push:
    branches: ['main']

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Giving test class names
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: RUN FAST
        run: python py/prioritize.py > test.txt
      - name: setup git config
        run: |
          git config user.name "FAST ACTION"
          git config user.email "<>"
      - name: commit
        run: |
          git add test.txt
          git commit -m "persisting test data"
          git push origin main